- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-inspector-grenade
        - ironic-inspector-tempest
        - ironic-inspector-tempest-discovery
        - ironic-inspector-tempest-managed
        # NOTE (rpittau) sadly temporary disabling the non-standalone-tempest
        # job until we got it fixed
        - ironic-inspector-non-standalone-tempest:
            voting: false
        - openstack-tox-functional-py36
        - bifrost-integration-tinyipa-ubuntu-bionic:
            voting: false
        - ironic-inspector-tox-bandit:
            voting: false
    gate:
      queue: ironic
      jobs:
        - ironic-inspector-grenade
        - ironic-inspector-tempest
        - ironic-inspector-tempest-discovery
        - ironic-inspector-tempest-managed
        - openstack-tox-functional-py36
