- project:
    templates:
      - check-requirements
      - openstack-cover-jobs-ironic-bugfix19
      - openstack-lower-constraints-master-branch-jobs
      - openstack-python3-yoga-jobs-ironic-bugfix19
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-inspector-grenade
        - ironic-inspector-tempest
        - ironic-inspector-tempest-discovery
        - ironic-inspector-tempest-managed-non-standalone
        - openstack-tox-functional-py38-yoga
        - bifrost-integration-tinyipa-ubuntu-focal:
            voting: false
        - ironic-inspector-tox-bandit:
            voting: false
    gate:
      jobs:
        - ironic-inspector-grenade
        - ironic-inspector-tempest
        - ironic-inspector-tempest-discovery
        - ironic-inspector-tempest-managed-non-standalone
        - openstack-tox-functional-py38-yoga
