- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-inspector-tempest
        - ironic-inspector-tempest-discovery
        - ironic-inspector-tempest-python3
        - openstack-tox-functional
        - openstack-tox-functional-py36
        - bifrost-integration-tinyipa-ubuntu-xenial:
            voting: false
    gate:
      queue: ironic
      jobs:
        - ironic-inspector-tempest
        - ironic-inspector-tempest-discovery
        - ironic-inspector-tempest-python3
        - openstack-tox-functional
        - openstack-tox-functional-py36
