- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-inspector-grenade-dsvm
        - ironic-inspector-tempest-dsvm-discovery
        - ironic-inspector-tempest-dsvm-python3
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - ironic-tempest-dsvm-ironic-inspector
        - openstack-tox-lower-constraints
        - openstack-tox-cover
    gate:
      queue: ironic
      jobs:
        - ironic-inspector-grenade-dsvm
        - ironic-inspector-tempest-dsvm-discovery
        - ironic-inspector-tempest-dsvm-python3
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - ironic-tempest-dsvm-ironic-inspector
        - openstack-tox-lower-constraints
        - openstack-tox-cover
